{{- define "renderWorkPackages" -}}
{{- $timeBlock := .timeBlock }}
{{- $root := .root }}
{{- range $idx, $item := .entries }}
---
apiVersion: openproject.org/v1alpha1
kind: WorkPackages
metadata:
  name: {{ printf "%s-%s-%s" $root.Release.Name (lower $timeBlock) (lower  ($item.name | replace " " "-")) | trunc 63 | trimSuffix "-" }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "openproject-workpackage.labels" $root | nindent 4 }}
spec:
  serverConfigRef:
    name: {{ $item.serverConfigRef }}
  subject: {{ $item.name | quote }}
  description: |
{{ $item.description | indent 4 }}
  schedule: {{ $item.schedule | quote }}
  projectID: {{ $item.projectID }}
  typeID: {{ $item.typeID }}
  epicID: {{ $item.epicID }}
{{- end }}
{{- end }}

{{- range $blockName, $entries := dict "daily" .Values.daily "monthly" .Values.monthly "quarterly" .Values.quarterly "annually" .Values.annually }}
  {{- if $entries }}
    {{- include "renderWorkPackages" (dict "entries" $entries "timeBlock" $blockName "root" $) }}
  {{- end }}
{{- end }}