{{ include "includeWorkPackages" . }}

{{- define "includeWorkPackages" -}}
{{- $timeBlocks := list "daily" "monthly" "quarterly" "annually" }}
{{- range $timeBlock := $timeBlocks }}
  {{- if (index $.Values $timeBlock) }}
    {{- $data := dict "root" $ "timeBlock" $timeBlock "entries" (index $.Values $timeBlock) "Values" $.Values }}
    {{- include "renderWorkPackages" $data }}
  {{- end }}
{{- end }}
{{- end -}}

{{- define "renderWorkPackages" -}}
{{- $root := .root }}
{{- $timeBlock := .timeBlock }}
{{- $entries := .entries }}
{{- $invs := .Values.inventories }}
{{- range $idx, $item := $entries }}

---
apiVersion: openproject.org/v1alpha1
kind: WorkPackages
metadata:
  name: {{ printf "%s-%s-%s" $root.Release.Name (lower $timeBlock) (lower ($item.subject | replace " " "-")) | trunc 63 | trimSuffix "-" }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "openproject-workpackage.labels" $root | nindent 4 }}
spec:
  serverConfigRef:
    name: {{ $item.serverConfigRef }}

  {{- if $item.schedule }}
  schedule: {{ $item.schedule | quote }}
  {{- end }}

  projectID: {{ $item.projectID }}
  typeID:    {{ $item.typeID }}
  epicID:    {{ $item.epicID }}
  subject:   {{ $item.subject }}

  {{- if $item.description }}
  description: |
{{ $item.description | nindent 4 }}
  {{- end }}

  {{- if $item.inventoryRef }}
  inventoryRef:
    name: {{ $item.inventoryRef }}
  {{- end }}
{{- end }}
{{- end }}

