---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.name }}-manager
  labels:
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}      
rules:
- apiGroups:
  - openproject.org
  resources:
  - serverconfigs
  - workpackages
  - cloudinventories
  - cloudinventoryreports  
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openproject.org
  resources:
  - serverconfigs/finalizers
  - workpackages/finalizers
  verbs:
  - update
- apiGroups:
  - openproject.org
  resources:
  - serverconfigs/status
  - workpackages/status
  - cloudinventories/status
  - cloudinventoryreports/status
  verbs:
  - get
  - patch
  - update
- apiGroups: [""]
  resources:
   - secrets
   - pods
   - namespaces
   - services
  verbs: 
   - get
   - list
   - watch
