apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openproject-operator.fullname" . }}
  labels:
    app: {{ include "openproject-operator.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "openproject-operator.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "openproject-operator.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          env:
          - name: DEBUG
            value: {{ .Values.debug | quote }}
          - name: DEFAULT_REQUEUE_TIME
            value: {{ .Values.operator.DefaultRequeueTime | quote }}
          - name: SHORT_REQUEUE_TIME
            value: {{ .Values.operator.ShortRequeueTime | quote }}
          - name: REQUEST_TIMEOUT
            value: {{ .Values.operator.RequestTimeout | quote }}
