# permissions for end users to view cloudinventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openproject-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudinventory-viewer-role
rules:
- apiGroups:
  - openproject.org
  resources:
  - cloudinventories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openproject.org
  resources:
  - cloudinventories/status
  verbs:
  - get
