---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - openproject.org
  resources:
  - cloudinventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openproject.org
  resources:
  - cloudinventories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openproject.org
  resources:
  - cloudinventoryreports
  verbs:
  - create
  - get
  - list
  - watch
