# permissions for end users to edit workpackages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openproject-k8s
    app.kubernetes.io/managed-by: kustomize
  name: workpackages-editor-role
rules:
- apiGroups:
  - openproject.org
  resources:
  - workpackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openproject.org
  resources:
  - workpackages/status
  verbs:
  - get
