replicaCount: 1
debug: false
image:
  repository: shrapk2/openproject-operator
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: openproject-operator

rbac:
  create: true

resources: {}

operator:
  DefaultRequeueTime: "1" #minutues
  ShortRequeueTime: "30" #seconds
  RequestTimeout: "90" #seconds
