replicaCount: 1
debug: false
image:
  repository: shrapk2/openproject-operator
  tag: v0.2.4
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: openproject-operator

rbac:
  create: true

resources: {}

operator:
  DefaultRequeueTime: "720m"
  ShortRequeueTime: "900s"
  RequestTimeout: "90s"
