apiVersion: openproject.org/v1alpha1
kind: ServerConfig
metadata:
  labels:
    app.kubernetes.io/name: openproject-k8s
    app.kubernetes.io/managed-by: kustomize
  name: serverconfig-sample
spec:
  # TODO(user): Add fields here
